# NumPy Creation 

### 1.0 Python NumPy
____

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.


#### 1.1 Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called `ndarray`, it provides a lot of supporting functions that make working with `ndarray` very easy.

Arrays are very frequently used in data science, where speed and resources are very important.


#### Numpy Arrays

1. Homogeneous Data: NumPy arrays store elements of the same data type, making them more compact and memory-efficient than lists.

1. Fixed Data Type: NumPy arrays have a fixed data type, reducing memory overhead by eliminating the need to store type information for each element.

1. Contiguous Memory: NumPy arrays store elements in adjacent memory locations, reducing fragmentation and allowing for efficient access.

1. Array Metadata: NumPy arrays have extra metadata like shape, strides, and data type. 
However, this overhead is usually smaller than the per-element overhead in lists.

1. Performance: NumPy arrays are optimized for numerical computations, with efficient element-wise operations and mathematical functions. These operations are implemented in C, resulting in faster performance than equivalent operations on lists.


#### 1.2 Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. This behavior is called locality of reference in computer science. This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

#### 1.3 Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

#### 1.4 Where is the NumPy Codebase?
The source code for NumPy is located at this github repository [https://github.com/numpy/numpy]


#### 1.5 Checking NumPy Version
The version string is stored under `__version__` attribute.

```python
import numpy as np
print(np.__version__)
```

**Numpy Vs Lists**

1. Unlike lists, arrays are of fixed size, and changing the size of an array will lead to the creation of a new array while the original array will be deleted.

1. All the elements in an array are of the same type.

1. Arrays are faster, more efficient, and require less syntax than standard Python sequences.

1. Arrays are stored in contiguous memory locations, making it easier to manipulate them.

Note: Various scientific and mathematical Python-based packages use Numpy. They might take input as an inbuilt Python sequence but they are likely to convert the data into a NumPy array to attain faster processing. This explains the need to understand NumPy.

**Why is the Numpy Array so Fast?** 

Numpy arrays are written mostly in C language. Being written in C, the arrays are stored in contiguous memory locations which makes them accessible and easier to manipulate. This means that you can get the performance level of a C code with the ease of writing a Python program.

1. Homogeneous Data: Arrays store elements of the same data type, making them more compact and memory-efficient than lists.
1. Fixed Data Type: Arrays have a fixed data type, reducing memory overhead by eliminating the need to store type information for each element.
3. Contiguous Memory: Arrays store elements in adjacent memory locations, reducing fragmentation and allowing for efficient access

In [1]:
import numpy as np
print(np.__version__)

1.21.2


### 2.0 Basic NumPy Array in Python
____

##### 2.1.0 NumPy Dimension Array
___

NumPy stands for Numerical Python. It is a Python library used for working with an array. In Python, we use the `list` for the array but it’s slow to process. NumPy array is a powerful N-dimensional array object and is used in linear algebra, Fourier transform, and random number capabilities. It provides an array object much faster than traditional Python lists.

Types of Array:
1. One Dimensional Array
1. Multi-Dimensional Array

In [1]:
# One Dimensional Array

import numpy as np
list = [1, 2, 3, 4, 5]
arr = np.array(list)

# Printing the list and array
print('List in python:', list)
print('1-D array in numpy:', arr)
print()

# check data types for list and array
print('Data type of list:', type(list))
print('Data type of array:', type(arr))

List in python: [1, 2, 3, 4, 5]
1-D array in numpy: [1 2 3 4 5]

Data type of list: <class 'list'>
Data type of array: <class 'numpy.ndarray'>


In [2]:
# Multi Dimensional Array

# importing numpy module
import numpy as np

# creating list 
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]

# creating numpy array
sample_array = np.array([list_1, list_2,list_3])

print("Numpy multi dimensional array in python\n",sample_array)


Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


> Note: The use of `[ ]` operators inside `np.array()` for multi-dimensional. Thus, the syntax for creating a NumPy array is `np.array([ ])`.

np.array ([a,b,c,d])

Where a, b, c, d are the elements of the array.

##### 2.2.0 Anatomy of NumPy Array
___

The NumPy array is a powerful N-dimensional array object that is in the form of rows and columns. The ndarray object is the main object of NumPy. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy, there are 6 basic anatomy elements:

1.	Axis: Axes are the different dimensions of an array. For a 2D array, the first axis is the rows and the second axis is the columns.  
	- Example: In a 2x3 array (2 rows, 3 columns), axis 0 refers to the rows, and axis 1 refers to the columns.

2.	Rank: Also known as the number of dimensions. It indicates how many dimensions the array has.
	- Example: A 2D array like [[1, 2, 3], [4, 5, 6]] has a rank of 2 because it has two dimensions (rows and columns).  

3.	Shape: This tells you how many elements are in each dimension of the array. It’s usually given as a tuple.
	- Example: The shape of a 2D array [[1, 2, 3], [4, 5, 6]] is (2, 3), meaning 2 rows and 3 columns.  

4.	Data Type: The type of elements stored in the array. Common data types include integers, floats, and strings.
	- Example: In the array np.array([1, 2, 3], dtype=int), the data type is int.

5.	Item Size: The size, in bytes, of each element in the array.
	- Example: If an array contains integers (typically 4 bytes each), the item size would be 4 bytes.
	
6.	Size: The total number of elements in the array. This is the product of the elements in the shape tuple.
	- Example: For the array [[1, 2, 3], [4, 5, 6]], the size is 6 (2 rows * 3 columns).
	
7.	Reshape: This operation changes the shape of an array without changing its data.
	- Example: If you have an array [1, 2, 3, 4] with shape (4,), you can reshape it to a 2x2 array [[1, 2], [3, 4]].

**Axis**
____

Axis in a NumPy array is the direction along the rows and columns, and it is defined by the number of dimensions in the array. it is the direction along which the elements of the array are processed.it starts from 0.

1. Axis 0 is the first axis and runs vertically downwards across the rows.
1. axis 1 is the second axis and runs horizontally across the columns.
1. axis 2 is the third axis and runs across the depth of the array.


Further Reading [https://www.sharpsightlabs.com/blog/numpy-axes-explained/]

![alt text](../../Teslim_python_png/axis.png)

**Shape**
___

The shape of an array is the number of elements stored along each dimension of the array. It is a tuple of integers showing the size of the array in each dimension. The shape of an array is the number of elements in each dimension. The shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.

The sytax for shape is `array.shape`

In [3]:
# importing numpy module
import numpy as np

# creating list 
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]

# creating numpy array
sample_array = np.array([list_1, list_2, list_3])

print(sample_array)
print()

# print shape of the array
print(sample_array.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

(3, 4)


In [4]:
import numpy as np

sample_array = np.array(
    [[0, 4, 2],
     [3, 4, 5],
     [23, 4, 5],
     [2, 34, 5],
     [5, 6, 7]]
)

print("shape of the array :",
      sample_array.shape)


shape of the array : (5, 3)


**Rank**
___

The rank of an array is the number of dimensions of the array. It is also called the number of axes. 

![alt text](../../Teslim_python_png/rank.png)

**Data Type**
___

When you create a NumPy array, each element in the array has a specific type of data associated with it, known as the data type or dtype. The dtype (data type) object provides detailed information about how the data is stored in memory. This is crucial for efficient computation, memory management, and ensuring the correct interpretation of data.

Definition: A `dtype` (short for data type) in NumPy is an object that defines the type of elements contained in a NumPy array. It specifies how the bytes in the memory block should be interpreted.

Components of `dtype`:
1. Type of the data (integer, float, Python object, etc.)
1. Size of the data (how many bytes is in e.g., int32, float64)
1. Byte order of the data (little-endian or big-endian)
1. Additional details like whether the data type is structured or not (e.g., composite types with multiple fields).


**Why is Data Type Important?**
1. Memory Allocation: The data type determines how much memory is allocated for each element in the array.
1. Data Interpretation: The data type specifies how the bytes in the memory block should be interpreted.
1. Computation: The data type affects how the data is processed during mathematical operations.
1. Data Integrity: Ensuring the correct data type helps maintain the integrity of the data by preventing operations that are not suitable for certain types (e.g., performing arithmetic on strings).

The syntax for dtype is `array.dtype`


Examples of dtype in NumPy

1. Simple Types:

    * `int32`: 32-bit integer
    * `float64`: 64-bit floating-point number
    * `bool`: Boolean value (True or False)



1. Complex Types: 
  
    * complex: Complex number with 64-bit floating-point real and imaginary parts
    * object: Python object type
    * string_: Fixed-length ASCII string type
    * unicode_: Fixed-length Unicode string type

1. Structured Types:
    
      * Structured data type with multiple fields
      * Each field has a name, data type, and optional shape
      * Allows for more complex data structures



**Creating Arrays with Specific dtype**
 
 When creating a NumPy array, you can specify the dtype:

In [5]:
import numpy as np

# Integer array: 32 bytes
int_array = np.array([1, 2, 3], dtype = np.int32)
print(int_array.dtype)  # Output: int32
print()

# integer array: 8 bytes
int_array = np.array([1, 2, 3], dtype = np.int8)
print(int_array.dtype)  # Output: int32
print()

# Floating-point array: 64 bytes
float_array = np.array([1.0, 2.0, 3.0], dtype = np.float64)
print(float_array.dtype)  # Output: float64
print()

# Boolean array: 1 byte
bool_array = np.array([True, False, True], dtype = np.bool_)
print(bool_array.dtype)  # Output: bool
print()

int32

int8

float64

bool



Understanding the dtype Object  

The dtype object contains all the information needed to interpret a block of memory:

In [6]:
dtype = np.dtype(np.int32)
print(dtype)  # Output: int32

# Properties of the dtype object
print(dtype.name)      # Output: 'int32'
print(dtype.type)      # Output: <class 'numpy.int32'>
print(dtype.itemsize)  # Output: 4 (bytes)

int32
int32
<class 'numpy.int32'>
4


### 3.0 Create Array in Python
____

NumPy arrays can have multiple dimensions, allowing users to store data in multilayered structures. The following are the Dimensionalities of array in Numpy:

* 0D (zero-dimensional): Scalar – A single element
* 1D (one-dimensional): Vector- A list of integers.
* 2D (two-dimensional): Matrix- A spreadsheet of data
* 3D (three-dimensional): ensor- Storing a color image



![alt text](../../Teslim_python_png/Numpy_ndarray.png)

##### 3.1.0 Create Array Object
___

NumPy array’s objects allow us to work with arrays in Python. The array object is called `ndarray`. The `array()` function of the NumPy library creates a ndarray.

In [42]:
import numpy as np 
arr = np.array([1,2,3,4,5,6])
print(arr)


[1 2 3 4 5 6]


##### 3.2.0 Create Numpy Array from a List
___

You can use the `np` alias to create ndarray of a list using the `array()` method.

In [43]:
li = [1,2,3,4]
numpyArr = np.array(li)
print(numpyArr)

[1 2 3 4]


The resulting array looks the same as a list but is a NumPy object. 

Example 2: Let’s take an example to check whether the numpyArr is a NumPy object or not. In this example, we are using the array() function to convert the list into a NumPy array and then check if it’s a NumPy object or not.

In [44]:
import numpy as np 

li = [1, 2, 3, 4] 
numpyArr = np.array(li) 

print("li =", li, "and type(li) =", type(li)) 
print()
print("numpyArr =", numpyArr, "and type(numpyArr) =", type(numpyArr))


li = [1, 2, 3, 4] and type(li) = <class 'list'>

numpyArr = [1 2 3 4] and type(numpyArr) = <class 'numpy.ndarray'>


##### 3.3.0 Create a Numpy Array from A Tuple
___

You can make ndarray from a tuple using a similar syntax.

In [45]:
import numpy as np 

tup = (1, 2, 3, 4) 
numpyArr = np.array(tup) 

print("tup =", tup, "and type(tup) =", type(tup)) 
print("numpyArr =", numpyArr, "and type(numpyArr) =", type(numpyArr)) 


tup = (1, 2, 3, 4) and type(tup) = <class 'tuple'>
numpyArr = [1 2 3 4] and type(numpyArr) = <class 'numpy.ndarray'>


##### 3.4.0 Create a Numpy Array using `fromitier()` function
___

The `numpy.fromiter()` function is used to create a new one-dimensional NumPy array from an iterable object, such as a list, tuple, or generator. It takes an iterable object as its first argument and an optional data type as its second argument.
Here's an example to illustrate its usage:

The sytax is as follows:

```python
numpy.fromiter(iterable, dtype, count=-1)
```
Where:
* iterable: An iterable object
* dtype: Data type of the returned array
* count: The number of items to read from iterable. The default is -1, which means all items are read.



In [46]:
# Example 1: Creating an array from a list
import numpy as np

# An iterable object (in this case, a list)
data = [1, 2, 3, 4, 5]

# Create a NumPy array from the list
array = np.fromiter(data, dtype=int)
print(array) 


[1 2 3 4 5]


In [1]:
# Example 2: Creating an array from a generator

import numpy as np

# A generator function
def generator():
    for i in range(5):
        yield i + 2

# Create a NumPy array from the generator
array = np.fromiter(generator(), dtype=int)
print(array) 
array.dtype 



[2 3 4 5 6]


dtype('int64')

In [48]:
# Example 3: Using the count parameter

import numpy as np

# An iterable object (in this case, a list)
data = [10, 20, 30, 40, 50]

# Create a NumPy array from the list, but only read the first 3 items
array = np.fromiter(data, dtype=int, count=3)
print(array)  # Output: [10 20 30]


[10 20 30]


**Advantages of Using `numpy.fromiter()`**
1. Efficiency: numpy.fromiter() can be more memory-efficient than first converting an iterable to a list and then creating a NumPy array, especially for large datasets.

2. Flexibility: It allows creating arrays directly from any iterable, including generators, which can save memory by not needing to store all elements in memory at once.

This function is particularly useful when working with large datasets or when data is being generated on the fly, making it a powerful tool in the NumPy library.

##### 3.5.0 Create a Numpy Array using `arange( )`
___

The `numpy.arange()` function in NumPy is used to generate arrays of evenly spaced values within a specified interval. It's similar to the built-in Python `range()` function, but it returns a NumPy array instead of a list, and it supports floating-point numbers.

The syntax for `numpy.arange()` is as follows:

```python
numpy.arange(start, stop, step, dtype=None)
```

Where:
* start: The starting value of the interval (inclusive)
* stop: The end value of the interval (exclusive)
* step: The step size between values (default is 1)
* dtype: The data type of the array (optional)


In [2]:
# Example 1: Basic Usage

import numpy as np

# Create an array of integers from 0 to 9
array = np.arange(10)
print(array)  


[0 1 2 3 4 5 6 7 8 9]


In [50]:
# Example 2: Specifying the start and stop parameters

import numpy as np

# Create an array of integers from 5 to 9
array = np.arange(5, 10)
print(array)  

[5 6 7 8 9]


In [3]:
# Example 3: Specifying the start, stop, and step parameters

import numpy as np

# Create an array of even integers from 0 to 9
array2 = np.arange(0, 10, 2)
print(array2)  
print()
print(array2.dtype)


[0 2 4 6 8]

int64


In [6]:
# Example 4: Using Floating Point Numbers

import numpy as np

# Create an array of floating point numbers from 0 to 1
array1 = np.arange(0, 1, 0.1)
print(array1)
print()  
print(array1.dtype)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]

float64


In [5]:
# Example 5: Specifying Data Type

import numpy as np

# Create an array of integers from 0 to 9 with data type float
array = np.arange(10, dtype=float)
print(array) 
print()
print(array.dtype)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

float64


##### 3.6.0 Create a Numpy Array using `nump.linspace( )`
___

The `numpy.linspace()` function in NumPy is used to generate an array of evenly spaced numbers over a specified interval. Unlike `numpy.arange()`, which specifies the step size, `numpy.linspace()` allows you to specify the number of elements you want between the start and stop values.

The syntax for `numpy.linspace()` is as follows:

```python
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis = 0)
```

Where:
* start: The starting value of the sequence
* stop: The end value of the sequence
* num: The number of samples to generate (default is 50)
* endpoint: Whether to include the stop value in the sequence (default is True)
* retstep: Whether to return the step size (default is False)
* dtype: The data type of the array (optional)
* axis: The axis in the result to store the samples (default is 0)



In [54]:
# Example 1: Basic Usage

import numpy as np

# Create an array of 5 evenly spaced values from 0 to 1
array = np.linspace(0, 1, num=5)
print(array)  

# In this example, it generates an array of 5 evenly spaced values from 0 to 1 (inclusive).


[0.   0.25 0.5  0.75 1.  ]


In [6]:
# Example 2: Specifying Endpoint

import numpy as np

# Create an array of 5 evenly spaced values from 0 to 1, excluding the endpoint
array = np.linspace(0, 100, num=10, endpoint=False)
print(array)  # Output: [0.  0.2 0.4 0.6 0.8]


[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [56]:
# Example 3: Returning Step Size

import numpy as np

# Create an array of 4 evenly spaced values from 0 to 2, and return the step size
array, step = np.linspace(0, 2, num=4, retstep=True)
print(array)  
print(step)   


# In this case, np.linspace(0, 2, num=4, retstep=True) generates an array of 4 evenly spaced values from 0 to 2, 
# and also returns the step size between the values.

[0.         0.66666667 1.33333333 2.        ]
0.6666666666666666


In [57]:
# Example 5: Using Axis Parameter
array = np.linspace(0, 1, num=5, axis=0)
print(array)  # Output: [0.   0.25 0.5  0.75 1.  ]


[0.   0.25 0.5  0.75 1.  ]


##### 3.7.0 Create a Numpy Array using `nump.empty( )`
___

The `numpy.empty()` function in NumPy is used to create a new array of a specified shape and data type, but it does not initialize the array elements with any particular values. This means the contents of the array are arbitrary and will consist of whatever values happen to be present at the allocated memory location.

the syntax is as follows:

```python
numpy.empty(shape, dtype=float, order='C')
```

Where:
* shape: The shape of the new array (e.g., (2, 3) for a 2x3 matrix)
* dtype: The data type of the array elements (default is float)
* order: The memory layout of the array (default is 'C' for row-major order)


**Important Note**

1. The `numpy.empty()` function is different from functions like `numpy.zeros()` or `numpy.ones()`, which initialize the array with zeros or ones, respectively.

1. Since `numpy.empty()` does not initialize the array, the elements will contain whatever random data happens to be in memory at the time of allocation. Therefore, you should assign values to the elements before using the array in computations.




In [10]:
import numpy as np

np.empty([4, 3], dtype = np.int32, order = 'f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [12]:
# Example 1: Creating an Uninitialized Array

import numpy as np

# Create a 2x3 array of floats, with uninitialized values
array = np.empty((2, 3))
print(array)

# In this example, np.empty((2, 3)) creates a 2x3 array with uninitialized values. 
# The values printed are whatever was in memory at the time.


[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# Example 2: Specifying Data Type

import numpy as np

# Create a 3x3 array of integers, with uninitialized values
array = np.empty((3, 3), dtype=int)
print(array)


[[4621819117588971520 4626322717216342016 4629137466983448576]
 [4630826316843712512 4632233691727265792 4633641066610819072]
 [4634626229029306368 4635329916471083008 4636033603912859648]]


**Use Cases**

1. Performance: np.empty() is faster than np.zeros() or np.ones() because it does not initialize the array elements.

1. Temporary Arrays: Useful for creating temporary arrays that will be immediately overwritten with calculated values.

1. Large Arrays: When creating large arrays where initialization is not needed, np.empty() can save time and resources.

However, it's important to be cautious when using np.empty(), as the uninitialized values can lead to unexpected behavior if you don't properly initialize the array elements before using them.







##### 3.8.0 Create a Numpy Array using `np.one( )`
___

 The `numpy.ones()` function in NumPy is used to create a new array of a specified shape and data type, where all the elements are initialized to the value 1.

The syntax for `numpy.ones()` is as follows:

```python
numpy.ones(shape, dtype=None, order='C')
```

Where:
* shape: The shape of the new array (e.g., (2, 3) for a 2x3 matrix)
* dtype: The data type of the array elements (default is None, which uses the default data type for the NumPy installation)
* order: The memory layout of the array (default is 'C' for row-major order)

**Use Cases**
1. Initialization: np.ones() is commonly used for initializing arrays before performing operations that require a specific starting value.
2. Placeholders: Useful for creating placeholder arrays for computations or data storage where the initial values are known to be 1.
3. Matrix Operations: Creating identity matrices or matrices for certain linear algebra operations where ones are needed.





In [61]:
# Example 1: Basic Usage

import numpy as np

# Create a 2x3 array of floats, filled with ones
array = np.ones((2, 3))
print(array)


[[1. 1. 1.]
 [1. 1. 1.]]


In [62]:
import numpy as np

np.ones([4, 3],
        dtype = np.int32,
        order = 'f')


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

##### 3.9.0 Create a Numpy Array using `np.zero( )`
___

The `numpy.zeros()` function in NumPy is used to create a new array of a specified shape and data type, where all the elements are initialized to the value 0.

The syntax for `numpy.zeros()` is as follows:

```python

numpy.zeros(shape, dtype=float, order='C')
```

Where:
* shape: The shape of the new array (e.g., (2, 3) for a 2x3 matrix)
* dtype: The data type of the array elements (default is float)
* order: The memory layout of the array (default is 'C' for row-major order)

**Use Cases**   

1. Initialization: np.zeros() is commonly used for initializing arrays before performing operations that require a specific starting value.
2. Placeholders: Useful for creating placeholder arrays for computations or data storage where the initial values are known to be 0.
3. Sparse Data: Often used in the context of sparse data structures where the majority of elements are zero.
4. Matrix Operations: Creating matrices for certain linear algebra operations where zeros are needed.
Using numpy.zeros() is straightforward and very useful for creating arrays that need to be initialized with the value 0.

In [63]:
# Example 1: Basic Usage

import numpy as np

# Create a 2x3 array of floats, filled with zeros
array = np.zeros((2, 3))
print(array)


[[0. 0. 0.]
 [0. 0. 0.]]


In [64]:
# Example 2: Specifying Data Type
import numpy as np

# Create a 3x3 array of integers, filled with zeros
array = np.zeros((3, 3), dtype=int)
print(array)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [65]:
# Example 4: Using Order Parameter

import numpy as np

# Create a 2x3 array with Fortran order (column-major order), filled with zeros
array = np.zeros((2, 3), order='F')
print(array)


[[0. 0. 0.]
 [0. 0. 0.]]


##### 3.10.0 Create a Numpy Array using `np.eye( )`
___

We can create a array using the `numpy.eye()` function in NumPy. The `numpy.eye()` function is used to create a 2D array with ones on the diagonal and zeros elsewhere. This function is commonly used to create identity matrices, which are square matrices with ones on the diagonal and zeros elsewhere. The sytax is as follows:

```python
numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
```

Where:
* N: The number of rows in the output array
* M: The number of columns in the output array (default is N)
* k: The index of the diagonal (default is 0, which refers to the main diagonal)
* dtype: The data type of the array elements (default is float)
* order: The memory layout of the array (default is 'C' for row-major order)

**Use Cases**

1. Identity Matrices: The primary use of np.eye() is to create identity matrices, which are square matrices with ones on the diagonal and zeros elsewhere.
2. Linear Algebra: Identity matrices are commonly used in linear algebra for operations like matrix multiplication, inversion, and solving systems of equations.
3. Placeholder Arrays: np.eye() can be used to create placeholder arrays for computations or data storage where the initial values are known to be an identity matrix.



In [66]:
# Example 1: Creating a 3x3 identity matrix:
import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
# Example 2: Creating a 4x4 identity matrix with a different diagonal offset:
import numpy as np

identity_matrix2 = np.eye(4, k=1)
print(identity_matrix2)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [68]:
# Creating a 3x4 matrix with ones on the diagonal:(non-square matrix)
import numpy as np

diagonal_matrix = np.eye(3, 4)
print(diagonal_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [69]:
# Diagonal Above the Main Diagonal: 
# Creating a 3x3 matrix with ones on the diagonal above the main diagonal:

import numpy as np
upper_diagonal_matrix = np.eye(3, 3, k=1)
print(upper_diagonal_matrix)


[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


##### 3.11.0 Create 1D NumPy Array using Random() Function
___

Wwe can use the `numpy.random.rand()` function to create a 1D NumPy array with random values. The `numpy.random.rand()` function generates random numbers from a uniform distribution over the range [0, 1). The syntax is as follows:

```python
numpy.random.rand(d0, d1, ..., dn)
```

Where:
* d0, d1, ..., dn: The dimensions of the output array (optional)


In [70]:
# Example 1: Creating a 3x3 matrix with random values:
import numpy as np

random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.55281858 0.35713377 0.0632484 ]
 [0.63578557 0.06997885 0.22252937]
 [0.99014729 0.57751571 0.47770637]]


Another example of random number generation is the `numpy.random.randn()` function, which generates random from a standard normal distribution. This distribution is also known as the Gaussian distribution or bell curve, which has a mean of 0 and a standard deviation of 1. The random numbere generated by this function are commonly used in statistical analysis and modeling, and refered as standard normal random numbers or z-score. The syntax is as follows:

```python
numpy.random.randn(d0, d1, ..., dn)
```

Where:
* d0, d1, ..., dn: The dimensions of the output array (optional)

In [71]:
# Example of standard normal distribution:
import numpy as np

random_matrix = np.random.randn(3, 3)
print(random_matrix)

[[ 0.98711405  0.0662489  -1.34837151]
 [ 0.1064459  -0.02411029 -0.68385355]
 [ 0.41034377 -0.00821735  0.74280311]]


##### 3.12.0 Create a Full NumPy Array using `np.full()`
___

We can create a full NumPy array using the `numpy.full()` function. The `numpy.full()` function is used to create a new array of a specified shape and data type, where all the elements are initialized to the specified fill value. The syntax is as follows:

```python
numpy.full(shape, fill_value, dtype=None, order='C')
```

Where:
* shape: The shape of the new array (e.g., (2, 3) for a 2x3 matrix)
* fill_value: The value to fill the array with
* dtype: The data type of the array elements (default is None, which uses the default data type for the NumPy installation)
* order: The memory layout of the array (default is 'C' for row-major order)


In [72]:
# Example of numpy.full() function

import numpy as np

# Create a 2x3 array filled with 7
array = np.full((3, 4), 7)
print(array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


**Create an Empty and a Full NumPy Array**

Sometimes there is a need to create an empty and full array simultaneously for a particular question. In this situation, we have two functions named `numpy.empty()` and `numpy. full()` to create an empty and full array. Here we will see different examples:

In [73]:
# Example 1: we create an empty array of 3X4 
# and a full array of 3X3 of INTEGER type.
import numpy as np

# Create an empty array
empa = np.empty((3, 4), dtype=int)
print("Empty Array")
print(empa)

# Create a full array
flla = np.full([3, 3], 55, dtype=int)
print("\n Full Array")
print(flla)


Empty Array
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

 Full Array
[[55 55 55]
 [55 55 55]
 [55 55 55]]


In [74]:
# Example 2: In the example, we create an empty array of 4X2 
# and a full array of 4X3 of INTEGER and FLOAT type.

import numpy as np


# Create an empty array
empa = np.empty([4, 2])
print("Empty Array")
print(empa)

# Create a full array
flla = np.full([4, 3], 95)
print("\n Full Array")
print(flla)


Empty Array
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

 Full Array
[[95 95 95]
 [95 95 95]
 [95 95 95]
 [95 95 95]]


##### 3.13.0 NumPy Array Function Creation
___


Aside the usual step stated above, there are other possibility of creating an array, and one of the common one is the the creation ofarray using the in-built function `array` function itself. The sytax for the using the array function is as follows:

```python
array(data type, value list)
```
* where `data type` is the type of the data to be stored in the array and `value list` is the list of values to be stored in the array.
 
* The array function can be used to create a NumPy array from a list or tuple. 

* The `data type` is represented by intial letter of the data type. 
 For example, 'i' for integer, 'f' for float, 'S' for string, 'b' for boolean, 'c' for complex number, 'O' for object, 'U' for unicode string, 'V' for raw data (void).




**Using Python's array Module**  

The array module in Python provides a basic way to create arrays with a specified data type.

In [75]:
import array

# Creating an array of integers
int_array = array.array('i', [1, 2, 3, 4, 5])
print("Integer array:", int_array)

# Creating an array of floats
float_array = array.array('f', [1.1, 2.2, 3.3, 4.4, 5.5])
print("Float array:", float_array)


Integer array: array('i', [1, 2, 3, 4, 5])
Float array: array('f', [1.100000023841858, 2.200000047683716, 3.299999952316284, 4.400000095367432, 5.5])


**Using NumPy for More Flexibility** 

While the array module is useful, NumPy is more powerful and flexible for numerical and scientific computing. You can achieve similar functionality using NumPy but with more capabilities.

In [76]:
import numpy as np

# Creating an array of integers
int_array = np.array([1, 2, 3, 4, 5], dtype=int)
print("NumPy Integer array:", int_array)

# Creating an array of floats
float_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=float)
print("NumPy Float array:", float_array)

# Creating an array of complex numbers
complex_array = np.array([1+2j, 3+4j, 5+6j], dtype=complex)
print("NumPy Complex array:", complex_array)


NumPy Integer array: [1 2 3 4 5]
NumPy Float array: [1.1 2.2 3.3 4.4 5.5]
NumPy Complex array: [1.+2.j 3.+4.j 5.+6.j]


**Detailed Example with NumPy**

Here’s a more detailed example that demonstrates creating arrays with different data types using NumPy:

In [77]:
import numpy as np

# Integer array
int_array = np.array([10, 20, 30, 40, 50], dtype=int)
print("NumPy Integer array:", int_array)
print("Data type of int_array:", int_array.dtype)
print()

# Float array
float_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=float)
print("NumPy Float array:", float_array)
print("Data type of float_array:", float_array.dtype)
print()

# Complex number array
complex_array = np.array([1+2j, 3+4j, 5+6j], dtype=complex)
print("NumPy Complex array:", complex_array)
print("Data type of complex_array:", complex_array.dtype)
print()

# Boolean array
bool_array = np.array([True, False, True, False], dtype=bool)
print("NumPy Boolean array:", bool_array)
print("Data type of bool_array:", bool_array.dtype)


NumPy Integer array: [10 20 30 40 50]
Data type of int_array: int64

NumPy Float array: [1.1 2.2 3.3 4.4 5.5]
Data type of float_array: float64

NumPy Complex array: [1.+2.j 3.+4.j 5.+6.j]
Data type of complex_array: complex128

NumPy Boolean array: [ True False  True False]
Data type of bool_array: bool


##### 3.15.0 Create a Numpy fromrecords() method
___

The `numpy.core.fromrecords()` function in NumPy is used to create a structured array from a list of tuples or a list of records. This function is particularly useful when you have tabular data and want to convert it into a NumPy structured array where each element can be accessed by a field name.

The syntax for numpy.core.fromrecords() is as follows:

```python
numpy.core.fromrecords(records, dtype=None, shape=None, formats=None, names=None, titles=None, aligned=False, byteorder=None, copy=True)
```

Where:
* recList: A list of tuples or a list of records from which to create the array. Each tuple should have the same length, corresponding to the number of fields in the record.

* dtype: (Optional) Data type descriptor of the resulting array. This can be specified as a list of tuples, with each tuple describing a field (name, type).

* shape: (Optional) The shape of the resulting array. If not specified, the shape is inferred from the length of the records.

* formats: (Optional) A list of data types for each field in the record. If dtype is not specified, this can be used to specify the data types of the fields.

* names: (Optional) A list of field names for the resulting array. If dtype is not specified, this can be used to specify the field names.

* titles: (Optional) A list of titles for the fields in the resulting array.

* aligned: (Optional) Whether the fields should be aligned in memory.

* byteorder: (Optional) The byte order of the resulting array.

In [78]:
import numpy as np

# Define a list of records
data = [(1, 2.5, 'Alice'), (2, 3.6, 'Bob'), (3, 4.2, 'Charlie')]

# Define the data type
dtype = [('id', 'i4'), ('score', 'f4'), ('name', 'U10')]

# Create a structured array from the list of records
structured_array = np.core.records.fromrecords(data, dtype=dtype)

print(structured_array)


[(1, 2.5, 'Alice') (2, 3.6, 'Bob') (3, 4.2, 'Charlie')]


**Accessing Fields**  
Once you have the structured array, you can access its fields by name:

In [79]:
print(structured_array['id'])    # Output: [1 2 3]
print(structured_array['score']) # Output: [2.5 3.6 4.2]
print(structured_array['name'])  # Output: ['Alice' 'Bob' 'Charlie']


[1 2 3]
[2.5 3.6 4.2]
['Alice' 'Bob' 'Charlie']


##### 3.14.0 NumPy Array Function Method 
___

Numpy has alot of in-built functions that can be used to create an array. The following are some of the in-built functions that can be used to create an array:

1. `np.zeros()`: This function is used to create an array of zeros. The syntax is `np.zeros(shape, dtype=float, order='C')`. The shape is the shape of the array, dtype is the data type, and order is the memory layout of the array.

1. `np.ones()`: This function is used to create an array of ones. The syntax is `np.ones(shape, dtype=None, order='C')`. The shape is the shape of the array, dtype is the data type, and order is the memory layout of the array.

Below is a table of all the in-built functions that can be used to create an array in NumPy:

**Methods for Array Creation in NumPy**

| Function        | Description                                                                                         |
|-----------------|-----------------------------------------------------------------------------------------------------|
| `empty()`       | Return a new array of given shape and type, without initializing entries                            |
| `empty_like()`  | Return a new array with the same shape and type as a given array                                    |
| `eye()`         | Return a 2-D array with ones on the diagonal and zeros elsewhere                                    |
| `identity()`    | Return the identity array                                                                           |
| `ones()`        | Return a new array of given shape and type, filled with ones                                        |
| `ones_like()`   | Return an array of ones with the same shape and type as a given array                               |
| `zeros()`       | Return a new array of given shape and type, filled with zeros                                       |
| `zeros_like()`  | Return an array of zeros with the same shape and type as a given array                              |
| `full_like()`   | Return a full array with the same shape and type as a given array                                   |
| `array()`       | Create an array                                                                                     |
| `asarray()`     | Convert the input to an array                                                                       |
| `asanyarray()`  | Convert the input to an ndarray, but pass ndarray subclasses through                                |
| `ascontiguousarray()` | Return a contiguous array in memory (C order)                                                 |
| `asmatrix()`    | Interpret the input as a matrix                                                                     |
| `copy()`        | Return an array copy of the given object                                                            |
| `frombuffer()`  | Interpret a buffer as a 1-dimensional array                                                         |
| `fromfile()`    | Construct an array from data in a text or binary file                                               |
| `fromfunction()`| Construct an array by executing a function over each coordinate                                     |
| `fromiter()`    | Create a new 1-dimensional array from an iterable object                                            |
| `fromstring()`  | A new 1-D array initialized from text data in a string                                              |
| `loadtxt()`     | Load data from a text file                                                                          |
| `arange()`      | Return evenly spaced values within a given interval                                                 |
| `linspace()`    | Return evenly spaced numbers over a specified interval                                              |
| `logspace()`    | Return numbers spaced evenly on a log scale                                                         |
| `geomspace()`   | Return numbers spaced evenly on a log scale (a geometric progression)                               |
| `meshgrid()`    | Return coordinate matrices from coordinate vectors                                                  |
| `mgrid()`       | nd_grid instance which returns a dense multi-dimensional “meshgrid”                                 |
| `ogrid()`       | nd_grid instance which returns an open multi-dimensional “meshgrid”                                 |
| `diag()`        | Extract a diagonal or construct a diagonal array                                                    |
| `diagflat()`    | Create a two-dimensional array with the flattened input as a diagonal                               |
| `tri()`         | An array with ones at and below the given diagonal and zeros elsewhere                              |
| `tril()`        | Lower triangle of an array                                                                          |
| `triu()`        | Upper triangle of an array                                                                          |
| `vander()`      | Generate a Vandermonde matrix                                                                       |
| `mat()`         | Interpret the input as a matrix                                                                     |
| `bmat()`        | Build a matrix object from a string, nested sequence, or array                                      |
